<?php

namespace Database\Seeders;

use App\Models\CustomerInformation;
use Illuminate\Database\Seeder;

class CustomerInformationSeeder extends Seeder
{
    public function run(): void
    {
        $solicitudes = [
            [
                'username' => 'viajes_sol',
                'agency_name' => 'Viajes Sol México',
                'legal_name' => 'Viajes Sol México S.A. de C.V.',
                'logo_url' => 'https://drive.google.com/file/d/1abc123/view',
                'password' => 'password123',
                'contact_person' => 'María González',
                'email' => 'contacto@viajessol.mx',
                'country' => 'México',
                'state' => 'Quintana Roo',
                'city' => 'Cancún',
                'phone' => '9981234567',
                'mobile' => '9987654321',
                'billing_manager' => 'María González',
                'billing_email' => 'contacto@viajessol.mx',
                'billing_address' => 'Av. Tulum 450, SM 4',
                'billing_country' => 'México',
                'billing_state' => 'Quintana Roo',
                'billing_city' => 'Cancún',
                'billing_zip_code' => '77500',
                'billing_phone' => '9981234567',
                'billing_phone_2' => null,
                'billing_mobile' => '9987654321',
                'billing_tax_id' => 'VSM980101ABC',
                'billing_same_as_contact' => true,
                'is_reviewed' => false,
                'is_accepted' => null,
            ],
            [
                'username' => 'mundo_azul',
                'agency_name' => 'Mundo Azul Travel',
                'legal_name' => 'Mundo Azul Travel S. de R.L.',
                'logo_url' => 'https://drive.google.com/file/d/2def456/view',
                'password' => 'password123',
                'contact_person' => 'Carlos Ramírez',
                'email' => 'carlos@mundoazul.com',
                'country' => 'México',
                'state' => 'Jalisco',
                'city' => 'Guadalajara',
                'phone' => '3331234567',
                'mobile' => '3339876543',
                'billing_manager' => 'Ana Ramírez',
                'billing_email' => 'facturacion@mundoazul.com',
                'billing_address' => 'Calle Morelos 120, Centro',
                'billing_country' => 'México',
                'billing_state' => 'Jalisco',
                'billing_city' => 'Guadalajara',
                'billing_zip_code' => '44100',
                'billing_phone' => '3335551234',
                'billing_phone_2' => '3335555678',
                'billing_mobile' => '3338889999',
                'billing_tax_id' => 'MAT850215XYZ',
                'billing_same_as_contact' => false,
                'is_reviewed' => false,
                'is_accepted' => null,
            ],
            [
                'username' => 'horizonte_tours',
                'agency_name' => 'Horizonte Tours',
                'legal_name' => 'Horizonte Tours S.A. de C.V.',
                'logo_url' => null,
                'password' => 'password123',
                'contact_person' => 'Laura Méndez',
                'email' => 'laura@horizontetours.mx',
                'country' => 'México',
                'state' => 'Ciudad de México',
                'city' => 'Ciudad de México',
                'phone' => '5551234567',
                'mobile' => '5557654321',
                'billing_manager' => 'Laura Méndez',
                'billing_email' => 'laura@horizontetours.mx',
                'billing_address' => 'Insurgentes Sur 800, Col. Del Valle',
                'billing_country' => 'México',
                'billing_state' => 'Ciudad de México',
                'billing_city' => 'Ciudad de México',
                'billing_zip_code' => '03100',
                'billing_phone' => '5551234567',
                'billing_phone_2' => null,
                'billing_mobile' => '5557654321',
                'billing_tax_id' => 'HTO900310DEF',
                'billing_same_as_contact' => true,
                'is_reviewed' => true,
                'is_accepted' => true,
            ],
            [
                'username' => 'caribe_express',
                'agency_name' => 'Caribe Express',
                'legal_name' => 'Caribe Express S.A. de C.V.',
                'logo_url' => 'https://drive.google.com/file/d/3ghi789/view',
                'password' => 'password123',
                'contact_person' => 'Roberto Sánchez',
                'email' => 'roberto@caribeexpress.com',
                'country' => 'México',
                'state' => 'Quintana Roo',
                'city' => 'Playa del Carmen',
                'phone' => '9841234567',
                'mobile' => '9847654321',
                'billing_manager' => 'Roberto Sánchez',
                'billing_email' => 'roberto@caribeexpress.com',
                'billing_address' => '5ta Avenida 28, Centro',
                'billing_country' => 'México',
                'billing_state' => 'Quintana Roo',
                'billing_city' => 'Playa del Carmen',
                'billing_zip_code' => '77710',
                'billing_phone' => '9841234567',
                'billing_phone_2' => null,
                'billing_mobile' => '9847654321',
                'billing_tax_id' => 'CEX870520GHI',
                'billing_same_as_contact' => true,
                'is_reviewed' => true,
                'is_accepted' => true,
            ],
            [
                'username' => 'ruta_dorada',
                'agency_name' => 'Ruta Dorada Viajes',
                'legal_name' => 'Ruta Dorada Viajes S.A. de C.V.',
                'logo_url' => 'https://drive.google.com/file/d/4jkl012/view',
                'password' => 'password123',
                'contact_person' => 'Patricia Herrera',
                'email' => 'patricia@rutadorada.mx',
                'country' => 'México',
                'state' => 'Nuevo León',
                'city' => 'Monterrey',
                'phone' => '8181234567',
                'mobile' => '8187654321',
                'billing_manager' => 'Jorge Herrera',
                'billing_email' => 'facturacion@rutadorada.mx',
                'billing_address' => 'Av. Constitución 500, Centro',
                'billing_country' => 'México',
                'billing_state' => 'Nuevo León',
                'billing_city' => 'Monterrey',
                'billing_zip_code' => '64000',
                'billing_phone' => '8185551234',
                'billing_phone_2' => null,
                'billing_mobile' => '8185559876',
                'billing_tax_id' => 'RDV920815JKL',
                'billing_same_as_contact' => false,
                'is_reviewed' => true,
                'is_accepted' => false,
            ],
            [
                'username' => 'explora_mx',
                'agency_name' => 'Explora México',
                'legal_name' => 'Explora México S.A. de C.V.',
                'logo_url' => null,
                'password' => 'password123',
                'contact_person' => 'Fernando López',
                'email' => 'fernando@exploramx.com',
                'country' => 'México',
                'state' => 'Yucatán',
                'city' => 'Mérida',
                'phone' => '9991234567',
                'mobile' => '9997654321',
                'billing_manager' => 'Fernando López',
                'billing_email' => 'fernando@exploramx.com',
                'billing_address' => 'Paseo de Montejo 300',
                'billing_country' => 'México',
                'billing_state' => 'Yucatán',
                'billing_city' => 'Mérida',
                'billing_zip_code' => '97000',
                'billing_phone' => '9991234567',
                'billing_phone_2' => null,
                'billing_mobile' => '9997654321',
                'billing_tax_id' => 'EMX880625MNO',
                'billing_same_as_contact' => true,
                'is_reviewed' => false,
                'is_accepted' => null,
            ],
            [
                'username' => 'luxury_stays',
                'agency_name' => 'Luxury Stays Agency',
                'legal_name' => 'Luxury Stays Agency S. de R.L.',
                'logo_url' => 'https://drive.google.com/file/d/5mno345/view',
                'password' => 'password123',
                'contact_person' => 'Valentina Ruiz',
                'email' => 'valentina@luxurystays.mx',
                'country' => 'México',
                'state' => 'Quintana Roo',
                'city' => 'Tulum',
                'phone' => '9845551234',
                'mobile' => '9845559876',
                'billing_manager' => 'Valentina Ruiz',
                'billing_email' => 'valentina@luxurystays.mx',
                'billing_address' => 'Carretera Tulum-Boca Paila Km 5',
                'billing_country' => 'México',
                'billing_state' => 'Quintana Roo',
                'billing_city' => 'Tulum',
                'billing_zip_code' => '77780',
                'billing_phone' => '9845551234',
                'billing_phone_2' => '9845554321',
                'billing_mobile' => '9845559876',
                'billing_tax_id' => 'LSA910410PQR',
                'billing_same_as_contact' => true,
                'is_reviewed' => true,
                'is_accepted' => true,
            ],
            [
                'username' => 'pacifico_viajes',
                'agency_name' => 'Pacífico Viajes',
                'legal_name' => 'Pacífico Viajes S.A. de C.V.',
                'logo_url' => 'https://drive.google.com/file/d/6pqr678/view',
                'password' => 'password123',
                'contact_person' => 'Miguel Torres',
                'email' => 'miguel@pacificoviajes.com',
                'country' => 'México',
                'state' => 'Baja California Sur',
                'city' => 'Los Cabos',
                'phone' => '6241234567',
                'mobile' => '6247654321',
                'billing_manager' => 'Sofía Torres',
                'billing_email' => 'facturacion@pacificoviajes.com',
                'billing_address' => 'Blvd. Marina 100, Centro',
                'billing_country' => 'México',
                'billing_state' => 'Baja California Sur',
                'billing_city' => 'Los Cabos',
                'billing_zip_code' => '23450',
                'billing_phone' => '6245551234',
                'billing_phone_2' => null,
                'billing_mobile' => '6245559876',
                'billing_tax_id' => 'PVI930720STU',
                'billing_same_as_contact' => false,
                'is_reviewed' => false,
                'is_accepted' => null,
            ],
            [
                'username' => 'andenes_travel',
                'agency_name' => 'Andenes Travel',
                'legal_name' => 'Andenes Travel S.A. de C.V.',
                'logo_url' => null,
                'password' => 'password123',
                'contact_person' => 'Daniela Castro',
                'email' => 'daniela@andenestravel.mx',
                'country' => 'México',
                'state' => 'Puebla',
                'city' => 'Puebla',
                'phone' => '2221234567',
                'mobile' => '2227654321',
                'billing_manager' => 'Daniela Castro',
                'billing_email' => 'daniela@andenestravel.mx',
                'billing_address' => 'Av. Juárez 150, Centro Histórico',
                'billing_country' => 'México',
                'billing_state' => 'Puebla',
                'billing_city' => 'Puebla',
                'billing_zip_code' => '72000',
                'billing_phone' => '2221234567',
                'billing_phone_2' => null,
                'billing_mobile' => '2227654321',
                'billing_tax_id' => 'ATR940315VWX',
                'billing_same_as_contact' => true,
                'is_reviewed' => true,
                'is_accepted' => false,
            ],
            [
                'username' => 'norte_agency',
                'agency_name' => 'Norte Agency',
                'legal_name' => 'Norte Agency S. de R.L. de C.V.',
                'logo_url' => 'https://drive.google.com/file/d/7stu901/view',
                'password' => 'password123',
                'contact_person' => 'Alejandro Vega',
                'email' => 'alejandro@norteagency.com',
                'country' => 'México',
                'state' => 'Chihuahua',
                'city' => 'Chihuahua',
                'phone' => '6141234567',
                'mobile' => '6147654321',
                'billing_manager' => 'Alejandro Vega',
                'billing_email' => 'alejandro@norteagency.com',
                'billing_address' => 'Av. Universidad 1200',
                'billing_country' => 'México',
                'billing_state' => 'Chihuahua',
                'billing_city' => 'Chihuahua',
                'billing_zip_code' => '31200',
                'billing_phone' => '6141234567',
                'billing_phone_2' => '6145554321',
                'billing_mobile' => '6147654321',
                'billing_tax_id' => 'NAG950820YZA',
                'billing_same_as_contact' => true,
                'is_reviewed' => false,
                'is_accepted' => null,
            ],
        ];

        foreach ($solicitudes as $solicitud) {
            CustomerInformation::updateOrCreate(
                ['username' => $solicitud['username']],
                [
                    ...$solicitud,
                    'active' => true,
                    'created_by' => 0,
                    'updated_by' => 0,
                ],
            );
        }
    }
}
